nodeSelector:
  customer: chowdeck

redis:
  nodeSelector:
    customer: chowdeck

autoscaling:
  enabled: false

replicaCount: 3

grpcIngress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
    external-dns.alpha.kubernetes.io/alias: "true"
    external-dns.alpha.kubernetes.io/hostname: chowdeck.refinery.honeydemo.io
    alb.ingress.kubernetes.io/backend-protocol-version: GRPC
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:428495456699:certificate/39f8cc4d-2cd5-4901-b091-250149430f76
    alb.ingress.kubernetes.io/conditions.refinery-grpc: >
      [{"field": "http-header", "httpHeaderConfig": {"httpHeaderName": "Content-Type", "values": ["application/grpc", "application/grpc+proto"]}}, {"field":"path-pattern","pathPatternConfig":{"values":["*"]}}]
    alb.ingress.kubernetes.io/actions.refinery-grpc: >
      {"type": "forward", "forwardConfig": { "targetGroups": [{"serviceName": {{ refinery | quote }}, "servicePort": "{{ 4317 }}"}] }}
  hosts:
    - host: chowdeck.refinery.honeydemo.io
      path: /
  tls:
    - secretName: refinery-tls
      hosts:
        - chowdeck.refinery.honeydemo.io

resources:
  limits:
    cpu: 3000m
    memory: 12Gi
  requests:
    cpu: 2000m
    memory: 12Gi

config:
  AddRuleReasonToTrace: true
  AdditionalErrorFields:
    - service.name
    - trace.trace_id
    - trace.span_id
  AddSpanCountToRoot: true
  TraceTimeout: 60s
  CacheOverrunStrategy: impact
  SampleCacheConfig:
    Type: cuckoo
  PeerManagement:
    Strategy: hash
  StressRelief:
    Mode: never
  InMemCollector:
    CacheCapacity: 1000000
    MaxAlloc: 10800000000
  Logger: honeycomb
  Metrics: honeycomb

  # Add Your API Key For Your Refinery Metrics Environment/Team
  HoneycombLogger:
    LoggerAPIKey: hcaik_01jwgxgr5m3xagn4fb2cz9mbrqe471y0kb40y7zks5a511dfsyhcznc41w
    LoggerDataset: refinery-logs
    LoggerHoneycombAPI: https://api.honeycomb.io
  HoneycombMetrics:
    MetricsAPIKey: hcaik_01jwgxgr5m3xagn4fb2cz9mbrqe471y0kb40y7zks5a511dfsyhcznc41w
    MetricsDataset: refinery-metrics
    MetricsHoneycombAPI: https://api.honeycomb.io
    MetricsReportingInterval: 30

rules:
  DryRun: false
  Sampler: DeterministicSampler
  SampleRate: 5

  # Environment Name Here (replace "production" if that's not your env name)
  production:
    Sampler: RulesBasedSampler
    rule:
      - name: Keep 500 status codes
        SampleRate: 1
        condition:
          - field: http.status_code
            operator: ">="
            value: 500
            datatype: int
      - name: Keep Type 2 GRPC Status Codes
        SampleRate: 1
        condition:
          - field: rpc.grpc.status_code
            operator: ">="
            value: 2
            datatype: int
      - name: Keep where error field exists
        SampleRate: 1
        condition:
          - field: error
            operator: exists
      - name: drop healthchecks
        drop: true
        condition:
          - field: http.target
            operator: starts-with
            value: /health
          - field: http.status_code
            operator: "="
            value: 200
            datatype: int
      - name: Keep long duration traces
        SampleRate: 1
        scope: span
        condition:
          - field: trace.parent_id
            operator: does-not-exist
          - field: duration_ms
            operator: ">="
            value: 1000
            datatype: int
      - name: Dynamically Sample 200s through 400s
        condition:
          - field: http.status_code
            operator: ">="
            value: 200
            datatype: int
        sampler:
          EMADynamicSampler:
            Sampler: EMADynamicSampler
            GoalSampleRate: 100
            FieldList:
              - service.name
              - http.target
              - http.status_code
              - http.method
      - name: Catchall rule
        sampler:
          TotalThroughputSampler:
            Sampler: TotalThroughputSampler
            GoalThroughputPerSec: 100
            ClearFrequencySec: 30
            FieldList:
              - service.name
              - http.status_code
              - status_code
